# Generated by Django 5.2.6 on 2025-12-28 19:31

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_actividad', models.CharField(max_length=100, unique=True, verbose_name='Actividad')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ['nombre_actividad'],
            },
        ),
        migrations.CreateModel(
            name='CargoEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cargo', models.CharField(max_length=100, unique=True, verbose_name='Cargo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción del Cargo')),
            ],
            options={
                'verbose_name': 'Cargo de Empleado',
                'verbose_name_plural': 'Cargos de Empleados',
                'ordering': ['nombre_cargo'],
            },
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_distrito', models.CharField(max_length=100, unique=True, verbose_name='Distrito')),
            ],
            options={
                'verbose_name': 'Distrito',
                'verbose_name_plural': 'Distritos',
                'ordering': ['nombre_distrito'],
            },
        ),
        migrations.CreateModel(
            name='Epp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_epp', models.CharField(max_length=100, unique=True, verbose_name='Nombre del EPP')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Costo')),
                ('unidad_medida', models.CharField(max_length=50, verbose_name='Unidad de Medida')),
            ],
            options={
                'verbose_name': 'EPP',
                'verbose_name_plural': 'EPPs',
                'ordering': ['nombre_epp'],
            },
        ),
        migrations.CreateModel(
            name='EstadoSST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=50, unique=True, verbose_name='Estado')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('color', models.CharField(default='#007bff', help_text='Color en formato hexadecimal (#FFFFFF)', max_length=7, verbose_name='Color')),
            ],
            options={
                'verbose_name': 'Estado SST',
                'verbose_name_plural': 'Estados SST',
                'ordering': ['estado'],
            },
        ),
        migrations.CreateModel(
            name='EstadoSuministro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_suministro', models.CharField(max_length=50, unique=True, verbose_name='Estado')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('color', models.CharField(default='#007bff', help_text='Color en formato hexadecimal (#FFFFFF)', max_length=7, verbose_name='Color')),
            ],
            options={
                'verbose_name': 'Estado Suministro',
                'verbose_name_plural': 'Estados Suministro',
                'ordering': ['estado_suministro'],
            },
        ),
        migrations.CreateModel(
            name='Insumos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_insumo', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Insumo')),
                ('unidad_medida', models.CharField(max_length=50, verbose_name='Unidad de Medida')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio Unitario')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
                'ordering': ['nombre_insumo'],
            },
        ),
        migrations.CreateModel(
            name='TipoIdentificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo', models.CharField(max_length=100, unique=True, verbose_name='Tipo de Identificación')),
            ],
            options={
                'verbose_name': 'Tipo de Identificación',
                'verbose_name_plural': 'Tipos de Identificación',
                'ordering': ['nombre_tipo'],
            },
        ),
        migrations.CreateModel(
            name='UnidadTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_transporte', models.CharField(max_length=100, verbose_name='Nombre del Transporte')),
                ('placa', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Formato de placa inválido. Use formatos: ABC-123, AB-1234, o A12-345', regex='^[A-Z]{3}-\\d{3}$|^[A-Z]{2}-\\d{4}$|^[A-Z]\\d{2}-\\d{3}$')], verbose_name='Placa')),
                ('costo_por_hora', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Costo por Hora')),
                ('tipo_vehiculo', models.CharField(choices=[('CAMIONETA', 'Camioneta'), ('CAMION', 'Camión'), ('MINIVAN', 'Minivan'), ('GRUA', 'Grúa'), ('AUTO', 'Automóvil')], default='CAMION', max_length=50, verbose_name='Tipo de Vehículo')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Unidad de Transporte',
                'verbose_name_plural': 'Unidades de Transporte',
                'ordering': ['tipo_vehiculo', 'nombre_transporte'],
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_identificacion', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Número de Identificación')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido_paterno', models.CharField(max_length=100, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(max_length=100, verbose_name='Apellido Materno')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=20, verbose_name='Estado')),
                ('fecha_ingreso', models.DateField(blank=True, null=True, verbose_name='Fecha de Ingreso')),
                ('fecha_cese', models.DateField(blank=True, null=True, verbose_name='Fecha de Cese')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.cargoempleado', verbose_name='Cargo')),
                ('tipo_identificacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.tipoidentificacion', verbose_name='Tipo de Identificación')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['apellido_paterno', 'apellido_materno', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='EmpleadoEpp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('fecha', models.DateField(verbose_name='Fecha de Asignación')),
                ('observacion', models.TextField(blank=True, verbose_name='Observaciones')),
                ('nombre_empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='epps_asignados', to='gestion.empleado')),
                ('nombre_epp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.epp')),
            ],
            options={
                'verbose_name': 'Empleado EPP',
                'verbose_name_plural': 'Empleado EPPs',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='HistorialSueldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sueldo', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('fecha_inicio', models.DateField(verbose_name='Vigente desde')),
                ('motivo', models.CharField(blank=True, help_text='Ej: Aumento anual, ascenso, etc.', max_length=255, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_sueldos', to='gestion.empleado')),
            ],
            options={
                'verbose_name': 'Historial de Sueldo',
                'verbose_name_plural': 'Historial de Sueldos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='SST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sst', models.CharField(db_index=True, max_length=7, unique=True, verbose_name='Código SST')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('monto_proyectado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto Proyectado')),
                ('monto_real', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto Real')),
                ('inicio_real', models.DateField(blank=True, null=True, verbose_name='Inicio Real')),
                ('fin_real', models.DateField(blank=True, null=True, verbose_name='Fin Real')),
                ('fecha_entrega_reporte_electrico_liquidacion', models.DateField(blank=True, null=True, verbose_name='Entrega Reporte Eléctrico Liquidación')),
                ('fecha_entrega_reporte_civil_liquidacion', models.DateField(blank=True, null=True, verbose_name='Entrega Reporte Civil Liquidación')),
                ('fecha_entrega_reporte_a_area_de_liquidacion', models.DateField(blank=True, null=True, verbose_name='Entrega Reporte a Área de Liquidación')),
                ('fecha_liquidacion_sistema', models.DateField(blank=True, null=True, verbose_name='Liquidación Sistema')),
                ('observacion', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('distrito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion.distrito', verbose_name='Distrito')),
                ('estado_sst', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion.estadosst', verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'SST',
                'verbose_name_plural': 'SSTs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgramacionPersonalSST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora_inicio', models.TimeField(verbose_name='Hora Inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora Fin')),
                ('observacion', models.TextField(blank=True, verbose_name='Observaciones')),
                ('estado', models.CharField(choices=[('PROGRAMADO', 'Programado'), ('EN_EJECUCION', 'En Ejecución'), ('EJECUTADO', 'Ejecutado'), ('PARALIZADO', 'Paralizado'), ('PENDIENTE', 'Pendiente')], default='PROGRAMADO', max_length=20, verbose_name='Estado')),
                ('nombre_actividad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.actividad')),
                ('nombre_empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.empleado')),
                ('sst', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programaciones_personal', to='gestion.sst')),
            ],
            options={
                'verbose_name': 'Programación Personal SST',
                'verbose_name_plural': 'Programaciones Personal SST',
                'ordering': ['-fecha', 'hora_inicio'],
                'unique_together': {('nombre_empleado', 'fecha', 'hora_inicio')},
            },
        ),
        migrations.CreateModel(
            name='SSTInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('fecha', models.DateField(verbose_name='Fecha de Uso')),
                ('observacion', models.TextField(blank=True, verbose_name='Observaciones')),
                ('nombre_insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.insumos')),
                ('sst', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sst_insumos', to='gestion.sst')),
            ],
            options={
                'verbose_name': 'SST Insumo',
                'verbose_name_plural': 'SST Insumos',
                'ordering': ['-fecha'],
                'unique_together': {('sst', 'nombre_insumo', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='Suministro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.PositiveIntegerField()),
                ('no_ot', models.CharField(max_length=20, verbose_name='N° OT')),
                ('suministro', models.CharField(db_index=True, max_length=20, verbose_name='Suministro')),
                ('medidor', models.CharField(blank=True, max_length=20, null=True)),
                ('marca_medidor', models.CharField(blank=True, max_length=20, null=True)),
                ('fase', models.CharField(blank=True, max_length=10, null=True)),
                ('potencia', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.TextField()),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('fecha_primer_envio', models.DateField(blank=True, null=True)),
                ('fecha_programada', models.DateField(blank=True, null=True)),
                ('hora_inicio_programada', models.TimeField(blank=True, null=True)),
                ('hora_fin_programada', models.TimeField(blank=True, null=True)),
                ('fecha_ejecucion', models.DateField(blank=True, null=True)),
                ('ejecutado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('contacto', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('observacion_cliente', models.TextField(blank=True, null=True)),
                ('observacion_contratista', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('distrito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion.distrito', verbose_name='Distrito')),
                ('estado_suministro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion.estadosuministro', verbose_name='Estado Suministro')),
                ('sst', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suministros', to='gestion.sst', verbose_name='SST')),
            ],
            options={
                'verbose_name': 'Suministro',
                'verbose_name_plural': 'Suministros',
                'ordering': ['item'],
                'unique_together': {('sst', 'suministro')},
            },
        ),
        migrations.CreateModel(
            name='ProgramacionTransporteSST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora_inicio', models.TimeField(verbose_name='Hora Inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora Fin')),
                ('observacion', models.TextField(blank=True, verbose_name='Observaciones')),
                ('estado', models.CharField(choices=[('PROGRAMADO', 'Programado'), ('EN_EJECUCION', 'En Ejecución'), ('TERMINADO', 'Terminado'), ('CANCELADO', 'Cancelado')], default='PROGRAMADO', max_length=20, verbose_name='Estado')),
                ('sst', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programaciones_transporte', to='gestion.sst')),
                ('nombre_transporte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.unidadtransporte')),
            ],
            options={
                'verbose_name': 'Programación Transporte SST',
                'verbose_name_plural': 'Programaciones Transporte SST',
                'ordering': ['-fecha', 'hora_inicio'],
                'unique_together': {('nombre_transporte', 'fecha', 'hora_inicio')},
            },
        ),
    ]
