# Generated by Django 5.2.6 on 2025-12-31 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suministro',
            options={'ordering': ['tipo_suministro', 'item'], 'verbose_name': 'Suministro', 'verbose_name_plural': 'Suministros'},
        ),
        migrations.AddField(
            model_name='suministro',
            name='fecha_identificacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de identificación'),
        ),
        migrations.AddField(
            model_name='suministro',
            name='motivo_adicional',
            field=models.TextField(blank=True, help_text='¿Por qué se agregó este suministro adicional?', null=True, verbose_name='Motivo del suministro adicional'),
        ),
        migrations.AddField(
            model_name='suministro',
            name='solicitado_por',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Solicitado por'),
        ),
        migrations.AddField(
            model_name='suministro',
            name='tipo_suministro',
            field=models.CharField(choices=[('ORIGINAL', 'Original'), ('ADICIONAL', 'Adicional')], default='ORIGINAL', max_length=20, verbose_name='Tipo de Suministro'),
        ),
    ]
