# Generated by Django 5.2.6 on 2026-01-03 17:47

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_suministro_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suministro',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto en soles del suministro', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Monto (S/)'),
        ),
        migrations.AlterField(
            model_name='sst',
            name='monto_proyectado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Suma automática de todos los suministros', max_digits=12, verbose_name='Monto Proyectado'),
        ),
        migrations.AlterField(
            model_name='sst',
            name='monto_real',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto Real'),
        ),
    ]
